//! # lau-ergodic-gradient
//!
//! Kimi's Theorem 3: gradient descent is the time-reversal of ergodic diffusion
//! generated by the Fokker-Planck operator.
//!
//! Core results:
//! - Fokker-Planck operator: ∂_t ρ = ∇·(ρ∇Φ) + Δρ
//! - Gradient descent as time-reversed Fokker-Planck flow
//! - Bakry-Émery CD(K,∞) curvature-dimension verification
//! - Spectral gap λ₁ ≥ K (Otto-Villani theorem)
//! - Entropy decay at rate e^{-2Kt} (log-Sobolev inequality)
//! - Wasserstein contraction W₂(S_t ρ, S_t σ) ≤ e^{-Kt} W₂(ρ, σ)
//! - JKO scheme: minimize ½τ W₂² + Ent_μ
//! - Gradient flow on parameter manifold (NN loss landscape)
//! - Ricci curvature from information geometry (Fisher metric)

use nalgebra::{DMatrix, DVector, RealField};
use serde::{Deserialize, Serialize};
use std::f64::consts::{E, PI};

// ─── Types and Core Structures ───────────────────────────────────────────────

/// Potential function Φ: ℝⁿ → ℝ represented by evaluation on a grid.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Potential {
    /// Values of Φ at grid points.
    pub values: Vec<f64>,
    /// Grid spacing (assumed uniform in each dimension).
    pub spacing: Vec<f64>,
    /// Number of grid points per dimension (same for all dims for simplicity).
    pub grid_size: usize,
    /// Number of dimensions.
    pub dim: usize,
}

impl Potential {
    /// Create a new zero potential on an n-dim grid.
    pub fn zeros(dim: usize, grid_size: usize, spacing: f64) -> Self {
        let total = grid_size.pow(dim as u32);
        Potential {
            values: vec![0.0; total],
            spacing: vec![spacing; dim],
            grid_size,
            dim,
        }
    }

    /// Create a quadratic potential Φ(x) = ½ K |x|² with given curvature.
    pub fn quadratic(dim: usize, grid_size: usize, spacing: f64, curvature: f64) -> Self {
        let total = grid_size.pow(dim as u32);
        let mut values = vec![0.0; total];
        let half = (grid_size as f64 - 1.0) / 2.0;
        for idx in 0..total {
            let mut r2 = 0.0;
            let mut rem = idx;
            for _ in 0..dim {
                let coord = (rem % grid_size) as f64 - half;
                r2 += coord * coord;
                rem /= grid_size;
            }
            values[idx] = 0.5 * curvature * r2 * spacing * spacing;
        }
        Potential {
            values,
            spacing: vec![spacing; dim],
            grid_size,
            dim,
        }
    }

    /// Evaluate Φ at a single multi-index.
    pub fn get(&self, multi_idx: &[usize]) -> f64 {
        let mut idx = 0;
        let mut stride = 1;
        for &d in multi_idx {
            idx += d * stride;
            stride *= self.grid_size;
        }
        self.values[idx]
    }

    /// Set Φ at a single multi-index.
    pub fn set(&mut self, multi_idx: &[usize], val: f64) {
        let mut idx = 0;
        let mut stride = 1;
        for &d in multi_idx {
            idx += d * stride;
            stride *= self.grid_size;
        }
        self.values[idx] = val;
    }

    /// Compute the gradient ∇Φ at grid points via central differences.
    pub fn gradient(&self) -> Vec<Vec<f64>> {
        let total = self.grid_size.pow(self.dim as u32);
        let mut grad = vec![vec![0.0; total]; self.dim];
        for idx in 0..total {
            let mut rem = idx;
            let mut coords = vec![0usize; self.dim];
            for d in 0..self.dim {
                coords[d] = rem % self.grid_size;
                rem /= self.grid_size;
            }
            for d in 0..self.dim {
                let h = self.spacing[d];
                let mut neighbor_plus = coords.clone();
                let mut neighbor_minus = coords.clone();
                if coords[d] + 1 < self.grid_size && coords[d] > 0 {
                    neighbor_plus[d] = coords[d] + 1;
                    neighbor_minus[d] = coords[d] - 1;
                    grad[d][idx] = (self.get(&neighbor_plus) - self.get(&neighbor_minus)) / (2.0 * h);
                } else if coords[d] + 1 < self.grid_size {
                    neighbor_plus[d] = coords[d] + 1;
                    grad[d][idx] = (self.get(&neighbor_plus) - self.values[idx]) / h;
                } else if coords[d] > 0 {
                    neighbor_minus[d] = coords[d] - 1;
                    grad[d][idx] = (self.values[idx] - self.get(&neighbor_minus)) / h;
                }
            }
        }
        grad
    }

    /// Compute the Hessian ∇²Φ (Laplacian trace) at grid points.
    pub fn laplacian(&self) -> Vec<f64> {
        let total = self.grid_size.pow(self.dim as u32);
        let mut lap = vec![0.0; total];
        for idx in 0..total {
            let mut rem = idx;
            let mut coords = vec![0usize; self.dim];
            for d in 0..self.dim {
                coords[d] = rem % self.grid_size;
                rem /= self.grid_size;
            }
            for d in 0..self.dim {
                let h = self.spacing[d];
                let h2 = h * h;
                let mut neighbor_plus = coords.clone();
                let mut neighbor_minus = coords.clone();
                let val = self.values[idx];
                if coords[d] + 1 < self.grid_size && coords[d] > 0 {
                    neighbor_plus[d] = coords[d] + 1;
                    neighbor_minus[d] = coords[d] - 1;
                    lap[idx] +=
                        (self.get(&neighbor_plus) - 2.0 * val + self.get(&neighbor_minus)) / h2;
                } else {
                    lap[idx] += 0.0; // boundary: no contribution
                }
            }
        }
        lap
    }

    /// Compute the minimum Hessian eigenvalue (gives Bakry-Émery curvature lower bound).
    pub fn min_hessian_eigenvalue(&self) -> f64 {
        // For simplicity: use central differences to estimate the Hessian diagonal
        // and return the minimum. For a quadratic potential this is exact.
        let total = self.grid_size.pow(self.dim as u32);
        let mut min_eig = f64::INFINITY;
        for idx in 0..total {
            let mut rem = idx;
            let mut coords = vec![0usize; self.dim];
            for d in 0..self.dim {
                coords[d] = rem % self.grid_size;
                rem /= self.grid_size;
            }
            for d in 0..self.dim {
                let h = self.spacing[d];
                let h2 = h * h;
                let val = self.values[idx];
                if coords[d] + 1 < self.grid_size && coords[d] > 0 {
                    let mut np = coords.clone();
                    let mut nm = coords.clone();
                    np[d] = coords[d] + 1;
                    nm[d] = coords[d] - 1;
                    let d2 = (self.get(&np) - 2.0 * val + self.get(&nm)) / h2;
                    if d2 < min_eig {
                        min_eig = d2;
                    }
                }
            }
        }
        if min_eig == f64::INFINITY { 0.0 } else { min_eig }
    }
}

/// Probability density ρ on a grid.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct Density {
    /// Density values (non-negative, sum to 1 with spacing weights).
    pub values: Vec<f64>,
    /// Grid spacing.
    pub spacing: Vec<f64>,
    /// Grid size per dim.
    pub grid_size: usize,
    /// Dimension.
    pub dim: usize,
}

impl Density {
    /// Uniform density.
    pub fn uniform(dim: usize, grid_size: usize, spacing: f64) -> Self {
        let total = grid_size.pow(dim as u32);
        let vol: f64 = spacing.powi(dim as i32) * total as f64;
        Density {
            values: vec![1.0 / vol; total],
            spacing: vec![spacing; dim],
            grid_size,
            dim,
        }
    }

    /// Gaussian density centered at origin.
    pub fn gaussian(dim: usize, grid_size: usize, spacing: f64, variance: f64) -> Self {
        let total = grid_size.pow(dim as u32);
        let half = (grid_size as f64 - 1.0) / 2.0;
        let mut values = vec![0.0; total];
        let norm = (2.0 * PI * variance).powi(dim as i32 / 2);
        // Actually let's use proper normalization
        let norm = (2.0 * PI * variance).powf(dim as f64 / 2.0);
        let mut sum = 0.0;
        for idx in 0..total {
            let mut r2 = 0.0;
            let mut rem = idx;
            for _ in 0..dim {
                let coord = (rem % grid_size) as f64 - half;
                r2 += coord * coord;
                rem /= grid_size;
            }
            let r2_scaled = r2 * spacing * spacing;
            values[idx] = (-r2_scaled / (2.0 * variance)).exp() / norm;
            sum += values[idx];
        }
        let cell_vol = spacing.powi(dim as i32);
        let total_mass = sum * cell_vol;
        for v in values.iter_mut() {
            *v /= total_mass;
        }
        Density {
            values,
            spacing: vec![spacing; dim],
            grid_size,
            dim,
        }
    }

    /// Create from values, normalizing to a probability density.
    pub fn from_values(dim: usize, grid_size: usize, spacing: f64, values: Vec<f64>) -> Self {
        let cell_vol = spacing.powi(dim as i32);
        let total: f64 = values.iter().sum::<f64>() * cell_vol;
        let normalized: Vec<f64> = if total > 0.0 {
            values.iter().map(|v| v / total).collect()
        } else {
            let n = values.len();
            vec![1.0 / (n as f64 * cell_vol); n]
        };
        Density {
            values: normalized,
            spacing: vec![spacing; dim],
            grid_size,
            dim,
        }
    }

    /// Total mass (should be ~1.0).
    pub fn total_mass(&self) -> f64 {
        let cell_vol = self.spacing.iter().product::<f64>();
        self.values.iter().sum::<f64>() * cell_vol
    }

    /// KL divergence D_KL(ρ || σ).
    pub fn kl_divergence(&self, other: &Density) -> f64 {
        let cell_vol = self.spacing.iter().product::<f64>();
        let mut kl = 0.0;
        for (&p, &q) in self.values.iter().zip(other.values.iter()) {
            if p > 0.0 && q > 0.0 {
                kl += p * (p / q).ln() * cell_vol;
            }
        }
        kl
    }

    /// Relative entropy H(ρ | μ) where μ is the Gibbs measure e^{-Φ}/Z.
    pub fn relative_entropy(&self, potential: &Potential) -> f64 {
        let cell_vol = self.spacing.iter().product::<f64>();
        let mut log_z = 0.0;
        let mut z_sum = 0.0;
        for &phi in &potential.values {
            let w = (-phi).exp();
            z_sum += w;
        }
        log_z = z_sum.ln() + cell_vol.ln() * self.dim as f64;

        let mut ent = 0.0;
        for (&rho, &phi) in self.values.iter().zip(potential.values.iter()) {
            if rho > 0.0 {
                ent += rho * rho.ln() * cell_vol;
                ent += rho * phi * cell_vol;
            }
        }
        ent += log_z;
        ent
    }

    /// Shannon entropy -∫ ρ ln ρ.
    pub fn entropy(&self) -> f64 {
        let cell_vol = self.spacing.iter().product::<f64>();
        let mut h = 0.0;
        for &rho in self.values.iter() {
            if rho > 0.0 {
                h -= rho * rho.ln() * cell_vol;
            }
        }
        h
    }

    /// Second moment ∫ |x|² ρ(x) dx (centered at grid midpoint).
    pub fn second_moment(&self) -> f64 {
        let cell_vol = self.spacing.iter().product::<f64>();
        let half = (self.grid_size as f64 - 1.0) / 2.0;
        let mut m2 = 0.0;
        for idx in 0..self.values.len() {
            let mut rem = idx;
            let mut r2 = 0.0;
            for _ in 0..self.dim {
                let coord = (rem % self.grid_size) as f64 - half;
                r2 += coord * coord;
                rem /= self.grid_size;
            }
            m2 += self.values[idx] * r2 * self.spacing[0].powi(2) * cell_vol;
        }
        m2
    }

    /// Mean position.
    pub fn mean(&self) -> Vec<f64> {
        let cell_vol = self.spacing.iter().product::<f64>();
        let half = (self.grid_size as f64 - 1.0) / 2.0;
        let mut mu = vec![0.0; self.dim];
        for idx in 0..self.values.len() {
            let mut rem = idx;
            for d in 0..self.dim {
                let coord = (rem % self.grid_size) as f64 - half;
                mu[d] += self.values[idx] * coord * self.spacing[d] * cell_vol;
                rem /= self.grid_size;
            }
        }
        mu
    }
}

// ─── Fokker-Planck Operator ──────────────────────────────────────────────────

/// Fokker-Planck operator: ∂_t ρ = ∇·(ρ∇Φ) + Δρ
///
/// This generates the time-reversal of gradient descent on Φ.
pub struct FokkerPlanck {
    pub potential: Potential,
    pub diffusion: f64,
}

impl FokkerPlanck {
    pub fn new(potential: Potential, diffusion: f64) -> Self {
        FokkerPlanck {
            potential,
            diffusion,
        }
    }

    /// Apply the Fokker-Planck operator to density ρ, returning ∂_t ρ.
    pub fn apply(&self, rho: &Density) -> Vec<f64> {
        let grad = self.potential.gradient();
        let lap_phi = self.potential.laplacian();
        let total = rho.values.len();
        let mut drho = vec![0.0; total];

        // ∂_t ρ = ∇·(ρ∇Φ) + D·Δρ
        // ∇·(ρ∇Φ) = ∇ρ·∇Φ + ρ·ΔΦ  (product rule)
        // Δρ = Laplacian of ρ

        // Gradient of ρ via central differences
        let grad_rho = {
            let mut g = vec![vec![0.0; total]; self.potential.dim];
            for idx in 0..total {
                let mut rem = idx;
                let mut coords = vec![0usize; self.potential.dim];
                for d in 0..self.potential.dim {
                    coords[d] = rem % self.potential.grid_size;
                    rem /= self.potential.grid_size;
                }
                for d in 0..self.potential.dim {
                    let h = self.potential.spacing[d];
                    if coords[d] + 1 < self.potential.grid_size && coords[d] > 0 {
                        let mut np = coords.clone();
                        let mut nm = coords.clone();
                        np[d] = coords[d] + 1;
                        nm[d] = coords[d] - 1;
                        let mut idx_p = 0;
                        let mut idx_m = 0;
                        let mut stride = 1;
                        for dd in 0..self.potential.dim {
                            idx_p += np[dd] * stride;
                            idx_m += nm[dd] * stride;
                            stride *= self.potential.grid_size;
                        }
                        g[d][idx] = (rho.values[idx_p] - rho.values[idx_m]) / (2.0 * h);
                    }
                }
            }
            g
        };

        // Laplacian of ρ
        let lap_rho = {
            let mut lap = vec![0.0; total];
            for idx in 0..total {
                let mut rem = idx;
                let mut coords = vec![0usize; self.potential.dim];
                for d in 0..self.potential.dim {
                    coords[d] = rem % self.potential.grid_size;
                    rem /= self.potential.grid_size;
                }
                for d in 0..self.potential.dim {
                    let h = self.potential.spacing[d];
                    let h2 = h * h;
                    if coords[d] + 1 < self.potential.grid_size && coords[d] > 0 {
                        let mut np = coords.clone();
                        let mut nm = coords.clone();
                        np[d] = coords[d] + 1;
                        nm[d] = coords[d] - 1;
                        let mut idx_p = 0;
                        let mut idx_m = 0;
                        let mut stride = 1;
                        for dd in 0..self.potential.dim {
                            idx_p += np[dd] * stride;
                            idx_m += nm[dd] * stride;
                            stride *= self.potential.grid_size;
                        }
                        lap[idx] += (rho.values[idx_p] - 2.0 * rho.values[idx] + rho.values[idx_m]) / h2;
                    }
                }
            }
            lap
        };

        for idx in 0..total {
            let mut drift = 0.0;
            for d in 0..self.potential.dim {
                drift += grad_rho[d][idx] * grad[d][idx] + rho.values[idx] * grad[d][idx]; // approximate ∇·(ρ∇Φ)
            }
            // Actually: ∇·(ρ∇Φ) = Σ_d ∂_d(ρ ∂_d Φ)
            // = Σ_d (∂_d ρ)(∂_d Φ) + ρ Σ_d ∂²_d Φ
            // = (∇ρ)·(∇Φ) + ρ·ΔΦ
            drift = 0.0;
            for d in 0..self.potential.dim {
                drift += grad_rho[d][idx] * grad[d][idx];
            }
            drift += rho.values[idx] * lap_phi[idx];

            drho[idx] = drift + self.diffusion * lap_rho[idx];
        }

        drho
    }

    /// Evolve density forward by time dt using Euler step.
    pub fn euler_step(&self, rho: &Density, dt: f64) -> Density {
        let drho = self.apply(rho);
        let new_values: Vec<f64> = rho.values
            .iter()
            .zip(drho.iter())
            .map(|(&r, &dr)| (r + dt * dr).max(0.0))
            .collect();
        Density::from_values(rho.dim, rho.grid_size, rho.spacing[0], new_values)
    }

    /// Evolve density forward by time T using N steps.
    pub fn evolve(&self, rho: &Density, t: f64, n_steps: usize) -> Density {
        let dt = t / n_steps as f64;
        let mut current = rho.clone();
        for _ in 0..n_steps {
            current = self.euler_step(&current, dt);
        }
        current
    }

    /// Gibbs stationary measure: μ ∝ e^{-Φ/D}.
    pub fn gibbs_measure(&self) -> Density {
        let beta = 1.0 / self.diffusion;
        let values: Vec<f64> = self.potential.values
            .iter()
            .map(|&phi| (-beta * phi).exp())
            .collect();
        Density::from_values(
            self.potential.dim,
            self.potential.grid_size,
            self.potential.spacing[0],
            values,
        )
    }
}

// ─── Gradient Descent as Time-Reversed Flow ──────────────────────────────────

/// Represents gradient descent as the time-reversal of Fokker-Planck flow.
pub struct TimeReversedGradientFlow {
    pub fp: FokkerPlanck,
}

impl TimeReversedGradientFlow {
    pub fn new(potential: Potential, diffusion: f64) -> Self {
        TimeReversedGradientFlow {
            fp: FokkerPlanck::new(potential, diffusion),
        }
    }

    /// The time-reversed Fokker-Planck equation gives gradient descent:
    /// ∂_t ρ = -∇·(ρ∇Φ) + D·Δρ  (reversed drift sign)
    pub fn reversed_apply(&self, rho: &Density) -> Vec<f64> {
        let grad = self.fp.potential.gradient();
        let lap_phi = self.fp.potential.laplacian();

        // Recompute gradient of ρ
        let total = rho.values.len();
        let grad_rho = {
            let mut g = vec![vec![0.0; total]; self.fp.potential.dim];
            for idx in 0..total {
                let mut rem = idx;
                let mut coords = vec![0usize; self.fp.potential.dim];
                for d in 0..self.fp.potential.dim {
                    coords[d] = rem % self.fp.potential.grid_size;
                    rem /= self.fp.potential.grid_size;
                }
                for d in 0..self.fp.potential.dim {
                    let h = self.fp.potential.spacing[d];
                    if coords[d] + 1 < self.fp.potential.grid_size && coords[d] > 0 {
                        let mut np = coords.clone();
                        let mut nm = coords.clone();
                        np[d] = coords[d] + 1;
                        nm[d] = coords[d] - 1;
                        let mut idx_p = 0;
                        let mut idx_m = 0;
                        let mut stride = 1;
                        for dd in 0..self.fp.potential.dim {
                            idx_p += np[dd] * stride;
                            idx_m += nm[dd] * stride;
                            stride *= self.fp.potential.grid_size;
                        }
                        g[d][idx] = (rho.values[idx_p] - rho.values[idx_m]) / (2.0 * h);
                    }
                }
            }
            g
        };

        // Reversed: flip drift sign → ∂_t ρ = -(∇ρ·∇Φ + ρΔΦ) + D·Δρ
        let lap_rho = {
            let mut lap = vec![0.0; total];
            for idx in 0..total {
                let mut rem = idx;
                let mut coords = vec![0usize; self.fp.potential.dim];
                for d in 0..self.fp.potential.dim {
                    coords[d] = rem % self.fp.potential.grid_size;
                    rem /= self.fp.potential.grid_size;
                }
                for d in 0..self.fp.potential.dim {
                    let h = self.fp.potential.spacing[d];
                    let h2 = h * h;
                    if coords[d] + 1 < self.fp.potential.grid_size && coords[d] > 0 {
                        let mut np = coords.clone();
                        let mut nm = coords.clone();
                        np[d] = coords[d] + 1;
                        nm[d] = coords[d] - 1;
                        let mut idx_p = 0;
                        let mut idx_m = 0;
                        let mut stride = 1;
                        for dd in 0..self.fp.potential.dim {
                            idx_p += np[dd] * stride;
                            idx_m += nm[dd] * stride;
                            stride *= self.fp.potential.grid_size;
                        }
                        lap[idx] += (rho.values[idx_p] - 2.0 * rho.values[idx] + rho.values[idx_m]) / h2;
                    }
                }
            }
            lap
        };

        let mut drho = vec![0.0; total];
        for idx in 0..total {
            let mut drift = 0.0;
            for d in 0..self.fp.potential.dim {
                drift += grad_rho[d][idx] * grad[d][idx];
            }
            drift += rho.values[idx] * lap_phi[idx];
            drho[idx] = -drift + self.fp.diffusion * lap_rho[idx];
        }
        drho
    }

    /// One step of gradient descent on the density (time-reversed flow).
    pub fn gradient_descent_step(&self, rho: &Density, dt: f64) -> Density {
        let drho = self.reversed_apply(rho);
        let new_values: Vec<f64> = rho.values
            .iter()
            .zip(drho.iter())
            .map(|(&r, &dr)| (r + dt * dr).max(0.0))
            .collect();
        Density::from_values(rho.dim, rho.grid_size, rho.spacing[0], new_values)
    }

    /// Run gradient descent for T total time with N steps.
    pub fn gradient_descent(&self, rho: &Density, t: f64, n_steps: usize) -> Density {
        let dt = t / n_steps as f64;
        let mut current = rho.clone();
        for _ in 0..n_steps {
            current = self.gradient_descent_step(&current, dt);
        }
        current
    }

    /// Verify the time-reversal relationship: forward FP followed by reversed = identity (approx).
    pub fn verify_time_reversal(&self, rho: &Density, dt: f64, steps: usize) -> f64 {
        let evolved = self.fp.evolve(rho, dt * steps as f64, steps);
        let reversed = self.gradient_descent(&evolved, dt * steps as f64, steps);
        // Compare to original
        let cell_vol = rho.spacing.iter().product::<f64>();
        let mut l2 = 0.0;
        for i in 0..rho.values.len() {
            let diff = rho.values[i] - reversed.values[i];
            l2 += diff * diff * cell_vol;
        }
        l2.sqrt()
    }
}

// ─── Bakry-Émery Curvature-Dimension ─────────────────────────────────────────

/// Bakry-Émery CD(K,∞) verification.
///
/// CD(K,∞) holds when Hess(Φ) ≥ K·I (in the sense of symmetric matrices).
/// For quadratic Φ(x) = ½K|x|², this holds exactly with CD(K,∞).
pub struct BakryEmery {
    pub potential: Potential,
}

impl BakryEmery {
    pub fn new(potential: Potential) -> Self {
        BakryEmery { potential }
    }

    /// Verify CD(K,∞): check that min eigenvalue of Hess(Φ) ≥ K.
    /// Returns the optimal (largest) K for which CD(K,∞) holds.
    pub fn optimal_curvature(&self) -> f64 {
        self.potential.min_hessian_eigenvalue()
    }

    /// Check if CD(K,∞) holds for a given K.
    pub fn check_cd(&self, k: f64) -> bool {
        self.optimal_curvature() >= k - 1e-10
    }

    /// Spectral gap from Otto-Villani theorem: λ₁ ≥ K when CD(K,∞).
    pub fn spectral_gap(&self) -> f64 {
        self.optimal_curvature()
    }

    /// Log-Sobolev inequality constant: LSI constant ≥ 2/K when CD(K,∞).
    pub fn log_sobolev_constant(&self) -> f64 {
        let k = self.optimal_curvature();
        if k > 0.0 {
            2.0 / k
        } else {
            f64::INFINITY
        }
    }

    /// Entropy decay rate: Ent(S_t ρ | μ) ≤ e^{-2Kt} Ent(ρ | μ).
    pub fn entropy_decay_bound(&self, t: f64, initial_entropy: f64) -> f64 {
        let k = self.optimal_curvature();
        initial_entropy * (-2.0 * k * t).exp()
    }

    /// Entropy decay at time t using actual density.
    pub fn entropy_decay(&self, rho: &Density, gibbs: &Density, t: f64, n_steps: usize, diffusion: f64) -> f64 {
        let fp = FokkerPlanck::new(self.potential.clone(), diffusion);
        let evolved = fp.evolve(rho, t, n_steps);
        evolved.kl_divergence(gibbs)
    }
}

// ─── Wasserstein Distance and Contraction ────────────────────────────────────

/// Wasserstein-2 distance utilities and contraction estimates.
pub struct WassersteinContraction {
    pub curvature_k: f64,
}

impl WassersteinContraction {
    pub fn new(curvature_k: f64) -> Self {
        WassersteinContraction { curvature_k }
    }

    /// Wasserstein contraction bound: W₂(S_t ρ, S_t σ) ≤ e^{-Kt} W₂(ρ, σ).
    pub fn contraction_bound(&self, t: f64, initial_w2: f64) -> f64 {
        initial_w2 * (-self.curvature_k * t).exp()
    }

    /// Discrete Wasserstein-2 distance (approximation via L2 on grid).
    pub fn discrete_w2(&self, rho: &Density, sigma: &Density) -> f64 {
        let cell_vol = rho.spacing.iter().product::<f64>();
        let half = (rho.grid_size as f64 - 1.0) / 2.0;
        let mut dist = 0.0;
        for idx in 0..rho.values.len() {
            let mut rem = idx;
            let mut r2 = 0.0;
            for _ in 0..rho.dim {
                let coord = (rem % rho.grid_size) as f64 - half;
                r2 += coord * coord;
                rem /= rho.grid_size;
            }
            let diff = rho.values[idx] - sigma.values[idx];
            // Simplified: use |ρ - σ| weighted by |x|² as a proxy
            dist += r2 * diff * diff * cell_vol * rho.spacing[0].powi(2);
        }
        dist.sqrt()
    }

    /// Verify contraction by evolving two densities and checking W₂ shrinks.
    pub fn verify_contraction(
        &self,
        rho: &Density,
        sigma: &Density,
        t: f64,
        n_steps: usize,
        diffusion: f64,
    ) -> (f64, f64, f64) {
        let fp = FokkerPlanck::new(
            Potential::quadratic(rho.dim, rho.grid_size, rho.spacing[0], self.curvature_k),
            diffusion,
        );
        let rho_t = fp.evolve(rho, t, n_steps);
        let sigma_t = fp.evolve(sigma, t, n_steps);
        let w2_initial = self.discrete_w2(rho, sigma);
        let w2_final = self.discrete_w2(&rho_t, &sigma_t);
        let bound = self.contraction_bound(t, w2_initial);
        (w2_initial, w2_final, bound)
    }
}

// ─── JKO Scheme ──────────────────────────────────────────────────────────────

/// Jordan-Kinderlehrer-Otto (JKO) scheme:
/// ρ^{n+1} = argmin_ρ { ½τ W₂²(ρ, ρⁿ) + Ent_μ(ρ) }
///
/// This is the variational formulation of the Fokker-Planck gradient flow.
pub struct JKOScheme {
    pub potential: Potential,
    pub diffusion: f64,
    pub tau: f64,
}

impl JKOScheme {
    pub fn new(potential: Potential, diffusion: f64, tau: f64) -> Self {
        JKOScheme {
            potential,
            diffusion,
            tau,
        }
    }

    /// Compute the JKO functional: ½τ W₂²(ρ, ρ_prev) + Ent_μ(ρ).
    /// Uses a simplified discrete approximation.
    pub fn jko_functional(&self, rho: &Density, rho_prev: &Density) -> f64 {
        // Approximate W₂² by L2-like transport cost
        let cell_vol = rho.spacing.iter().product::<f64>();
        let half = (rho.grid_size as f64 - 1.0) / 2.0;
        let mut w2_sq = 0.0;
        for idx in 0..rho.values.len() {
            let mut rem = idx;
            let mut r2 = 0.0;
            for _ in 0..rho.dim {
                let coord = (rem % rho.grid_size) as f64 - half;
                r2 += coord * coord;
                rem /= rho.grid_size;
            }
            let diff = rho.values[idx] - rho_prev.values[idx];
            w2_sq += r2 * rho.spacing[0].powi(2) * diff.abs() * cell_vol;
        }

        let ent = rho.relative_entropy(&self.potential);
        0.5 * self.tau * w2_sq + ent
    }

    /// One JKO step via proximal iteration.
    /// Uses entropic regularization (Sinkhorn-like) for tractability.
    pub fn jko_step(&self, rho_prev: &Density) -> Density {
        // Simplified: proximal map with entropy
        // ρ^{n+1} ≈ exp(-τ Φ) · K_τ * ρ^n / Z
        // where K_τ is the heat kernel at time τ
        let beta = 1.0 / self.diffusion;
        let total = rho_prev.values.len();
        let cell_vol = rho_prev.spacing.iter().product::<f64>();

        // Apply heat kernel (Gaussian blur) + potential
        let sigma2 = 2.0 * self.diffusion * self.tau;
        let kernel_radius = (3.0 * sigma2.sqrt() / rho_prev.spacing[0]).ceil() as usize;

        let mut new_values = vec![0.0; total];
        for idx in 0..total {
            let mut rem = idx;
            let mut coords = vec![0usize; self.dim()];
            for d in 0..self.dim() {
                coords[d] = rem % rho_prev.grid_size;
                rem /= rho_prev.grid_size;
            }

            let mut val = 0.0;
            // Apply Gaussian blur within kernel_radius
            self._blur_accumulate(
                &mut val, &coords, &rho_prev, &coords, 0,
                kernel_radius, sigma2,
            );

            // Multiply by Gibbs factor
            let gibbs = (-beta * self.potential.values[idx] * self.tau).exp();
            new_values[idx] = val * gibbs;
        }

        Density::from_values(self.dim(), rho_prev.grid_size, rho_prev.spacing[0], new_values)
    }

    fn dim(&self) -> usize {
        self.potential.dim
    }

    fn _blur_accumulate(
        &self, acc: &mut f64, center: &[usize], rho: &Density,
        current: &[usize], dim_idx: usize, radius: usize, sigma2: f64,
    ) {
        if dim_idx == center.len() {
            // Compute Gaussian weight
            let mut r2 = 0.0;
            let mut idx = 0;
            let mut stride = 1;
            for d in 0..center.len() {
                let diff = current[d] as f64 - center[d] as f64;
                r2 += diff * diff * rho.spacing[d].powi(2);
                idx += current[d] * stride;
                stride *= rho.grid_size;
            }
            let weight = (-r2 / (2.0 * sigma2)).exp() / (2.0 * PI * sigma2).powf(rho.dim as f64 / 2.0);
            *acc += weight * rho.values[idx];
            return;
        }
        let lo = center[dim_idx].saturating_sub(radius);
        let hi = (center[dim_idx] + radius + 1).min(rho.grid_size);
        for k in lo..hi {
            let mut next = current.to_vec();
            next[dim_idx] = k;
            self._blur_accumulate(acc, center, rho, &next, dim_idx + 1, radius, sigma2);
        }
    }

    /// Run N JKO steps.
    pub fn evolve(&self, rho: &Density, n_steps: usize) -> Density {
        let mut current = rho.clone();
        for _ in 0..n_steps {
            current = self.jko_step(&current);
        }
        current
    }

    /// Verify JKO functional decreases monotonically.
    pub fn verify_monotone_decrease(&self, rho: &Density, n_steps: usize) -> Vec<f64> {
        let mut functionals = Vec::new();
        let mut current = rho.clone();
        for _ in 0..n_steps {
            let next = self.jko_step(&current);
            functionals.push(self.jko_functional(&next, &current));
            current = next;
        }
        functionals
    }
}

// ─── Gradient Flow on Parameter Manifold ─────────────────────────────────────

/// Neural network loss landscape modeled as a Riemannian manifold.
/// The loss function L(θ) defines a potential on parameter space.
#[derive(Clone, Serialize, Deserialize)]
pub struct ParameterManifold {
    /// Current parameter vector θ.
    pub theta: DVector<f64>,
    /// Learning rate.
    pub lr: f64,
    /// Loss function gradient (externally computed).
    pub gradient: DVector<f64>,
    /// Fisher information matrix (metric tensor).
    pub fisher: DMatrix<f64>,
}

impl ParameterManifold {
    pub fn new(theta: DVector<f64>, lr: f64) -> Self {
        let n = theta.len();
        ParameterManifold {
            theta,
            lr,
            gradient: DVector::zeros(n),
            fisher: DMatrix::identity(n, n),
        }
    }

    /// Natural gradient descent: θ ← θ - lr · F^{-1} ∇L(θ).
    pub fn natural_gradient_step(&mut self) -> DVector<f64> {
        if let Some(f_inv) = self.fisher.clone().try_inverse() {
            let nat_grad = &f_inv * &self.gradient;
            self.theta -= self.lr * &nat_grad;
        } else {
            self.theta -= self.lr * &self.gradient;
        }
        self.theta.clone()
    }

    /// Standard gradient descent step: θ ← θ - lr · ∇L(θ).
    pub fn gradient_step(&mut self) -> DVector<f64> {
        self.theta -= self.lr * &self.gradient;
        self.theta.clone()
    }

    /// Set loss gradient from a function eval. (Simplified: user provides gradient.)
    pub fn set_gradient(&mut self, grad: DVector<f64>) {
        self.gradient = grad;
    }

    /// Update Fisher information matrix.
    pub fn set_fisher(&mut self, fisher: DMatrix<f64>) {
        self.fisher = fisher;
    }

    /// Compute Riemannian gradient: F^{-1} ∇L(θ).
    pub fn riemannian_gradient(&self) -> DVector<f64> {
        if let Some(f_inv) = self.fisher.clone().try_inverse() {
            &f_inv * &self.gradient
        } else {
            self.gradient.clone()
        }
    }

    /// Parameter space norm: ‖v‖_F = √(v^T F v).
    pub fn riemannian_norm(&self, v: &DVector<f64>) -> f64 {
        let fv = &self.fisher * v;
        v.dot(&fv).max(0.0).sqrt()
    }
}

// ─── Fisher Metric and Ricci Curvature ───────────────────────────────────────

/// Ricci curvature from information geometry using the Fisher metric.
///
/// For an exponential family p(x|θ) = h(x) exp(θ·T(x) - A(θ)),
/// the Fisher metric is g_{ij} = ∂²A/(∂θ_i ∂θ_j), and the
/// Ricci curvature tensor can be computed from the Christoffel symbols.
pub struct FisherRicci {
    /// Fisher information matrix g_{ij}.
    pub fisher: DMatrix<f64>,
    /// Christoffel symbols of the first kind: Γ_{ijk} = ½(∂_i g_{jk} + ∂_j g_{ik} - ∂_k g_{ij}).
    /// Stored as a vector of matrices, one per index.
    pub christoffel: Vec<DMatrix<f64>>,
}

impl FisherRicci {
    /// Create from Fisher matrix (assumes Christoffel symbols are zero for constant Fisher).
    pub fn from_fisher(fisher: DMatrix<f64>) -> Self {
        let n = fisher.nrows();
        FisherRicci {
            christoffel: vec![DMatrix::zeros(n, n); n],
            fisher,
        }
    }

    /// Create from log-partition derivatives for an exponential family.
    /// fisher[i][j] = ∂²A/(∂θ_i ∂θ_j), christoffel_approx[i][j][k] from finite differences.
    pub fn from_exponential_family(
        d2_a: DMatrix<f64>,
        d3_a: &[DMatrix<f64>], // d3_a[k] = ∂³A/(∂θ_k ∂θ_i ∂θ_j)
    ) -> Self {
        let n = d2_a.nrows();
        let fisher = d2_a;
        // Γ_{ijk} = ½ Σ_k (∂³A_{ij}/∂θ_k) ... using the metric
        // Γ^k_{ij} = ½ g^{kl} (∂_i g_{jl} + ∂_j g_{il} - ∂_l g_{ij})
        // For exponential family: ∂_k g_{ij} = ∂³A/(∂θ_k ∂θ_i ∂θ_j)
        let mut christoffel = vec![DMatrix::zeros(n, n); n];
        if let Some(g_inv) = fisher.clone().try_inverse() {
            for k in 0..n {
                for i in 0..n {
                    for j in 0..n {
                        let mut gamma = 0.0;
                        for l in 0..n {
                            let d_g_jl = d3_a.get(k).map(|m| m[(j, l)]).unwrap_or(0.0);
                            let d_g_il = d3_a.get(k).map(|m| m[(i, l)]).unwrap_or(0.0);
                            let d_g_ij = d3_a.get(l).map(|m| m[(i, j)]).unwrap_or(0.0);
                            gamma += g_inv[(k, l)] * (d_g_jl + d_g_il - d_g_ij);
                        }
                        christoffel[k][(i, j)] = 0.5 * gamma;
                    }
                }
            }
        }
        FisherRicci { fisher, christoffel }
    }

    /// Compute Ricci curvature tensor: Ric_{ij} = R^k_{ikj}
    /// where R^l_{ijk} = ∂_k Γ^l_{ij} - ∂_j Γ^l_{ik} + Γ^l_{ks} Γ^s_{ij} - Γ^l_{js} Γ^s_{ik}
    /// For constant Christoffel (affine connection), R^l_{ijk} = Γ^l_{ks} Γ^s_{ij} - Γ^l_{js} Γ^s_{ik}
    pub fn ricci_tensor(&self) -> DMatrix<f64> {
        let n = self.fisher.nrows();
        let mut ricci = DMatrix::zeros(n, n);

        for i in 0..n {
            for j in 0..n {
                let mut rij = 0.0;
                for k in 0..n {
                    // R^k_{ikj} with constant Christoffel:
                    // = Σ_s (Γ^k_{ks} Γ^s_{ij} - Γ^k_{js} Γ^s_{ik})
                    for s in 0..n {
                        rij += self.christoffel[k][(k, s)] * self.christoffel[s][(i, j)]
                            - self.christoffel[k][(j, s)] * self.christoffel[s][(i, k)];
                    }
                }
                ricci[(i, j)] = rij;
            }
        }
        ricci
    }

    /// Scalar curvature: R = g^{ij} Ric_{ij}.
    pub fn scalar_curvature(&self) -> f64 {
        let ricci = self.ricci_tensor();
        if let Some(g_inv) = self.fisher.clone().try_inverse() {
            (&g_inv * &ricci).trace()
        } else {
            0.0
        }
    }

    /// Ricci curvature in a direction v: Ric(v,v) / g(v,v).
    pub fn ricci_curvature_direction(&self, v: &DVector<f64>) -> f64 {
        let ricci = self.ricci_tensor();
        let rv = &ricci * v;
        let gv = &self.fisher * v;
        let num = v.dot(&rv);
        let den = v.dot(&gv);
        if den.abs() > 1e-15 { num / den } else { 0.0 }
    }

    /// Lower bound on Ricci curvature (minimum over unit directions).
    /// This gives the CD(K,∞) curvature K for the parameter manifold.
    pub fn min_ricci_curvature(&self) -> f64 {
        let ricci = self.ricci_tensor();
        // For a symmetric matrix, min Ricci curvature = min eigenvalue of (g^{-1} Ricci)
        if let Some(g_inv) = self.fisher.clone().try_inverse() {
            let m = &g_inv * &ricci;
            // Power iteration for min eigenvalue
            let n = m.nrows();
            if n == 0 { return 0.0; }
            let eigvals = m.symmetric_eigenvalues();
            eigvals.iter().cloned().fold(f64::INFINITY, f64::min)
        } else {
            0.0
        }
    }

    /// Check if the parameter manifold satisfies CD(K,∞).
    pub fn check_cd(&self, k: f64) -> bool {
        self.min_ricci_curvature() >= k - 1e-10
    }
}

// ─── PLATO Agent Application ─────────────────────────────────────────────────

/// PLATO agent belief update and convergence analysis.
///
/// Models the agent's belief distribution over parameters as a density
/// evolving via Fokker-Planck, with convergence guarantees from CD(K,∞).
#[derive(Clone)]
pub struct PlatoBeliefUpdate {
    pub curvature_k: f64,
    pub diffusion: f64,
    pub dim: usize,
    pub grid_size: usize,
    pub spacing: f64,
}

impl PlatoBeliefUpdate {
    pub fn new(curvature_k: f64, diffusion: f64, dim: usize, grid_size: usize, spacing: f64) -> Self {
        PlatoBeliefUpdate {
            curvature_k,
            diffusion,
            dim,
            grid_size,
            spacing,
        }
    }

    /// Initialize a Gaussian belief centered at origin.
    pub fn init_gaussian_belief(&self, variance: f64) -> Density {
        Density::gaussian(self.dim, self.grid_size, self.spacing, variance)
    }

    /// Evolve belief via Fokker-Planck (ergodic diffusion).
    pub fn evolve_belief(&self, belief: &Density, t: f64, n_steps: usize) -> Density {
        let potential = Potential::quadratic(self.dim, self.grid_size, self.spacing, self.curvature_k);
        let fp = FokkerPlanck::new(potential, self.diffusion);
        fp.evolve(belief, t, n_steps)
    }

    /// Convergence rate bound: e^{-Kt} for W₂.
    pub fn convergence_rate(&self, t: f64) -> f64 {
        (-self.curvature_k * t).exp()
    }

    /// Entropy convergence rate bound: e^{-2Kt}.
    pub fn entropy_convergence_rate(&self, t: f64) -> f64 {
        (-2.0 * self.curvature_k * t).exp()
    }

    /// Spectral gap: λ₁ ≥ K.
    pub fn spectral_gap(&self) -> f64 {
        self.curvature_k
    }

    /// Time to reach ε-accuracy in W₂ distance.
    pub fn mixing_time_w2(&self, epsilon: f64, initial_w2: f64) -> f64 {
        if self.curvature_k > 0.0 {
            (initial_w2 / epsilon).ln() / self.curvature_k
        } else {
            f64::INFINITY
        }
    }

    /// Time to reach ε-accuracy in entropy.
    pub fn mixing_time_entropy(&self, epsilon: f64, initial_entropy: f64) -> f64 {
        if self.curvature_k > 0.0 {
            (initial_entropy / epsilon).ln() / (2.0 * self.curvature_k)
        } else {
            f64::INFINITY
        }
    }

    /// Full convergence analysis.
    pub fn convergence_analysis(&self, t: f64) -> ConvergenceReport {
        ConvergenceReport {
            curvature_k: self.curvature_k,
            spectral_gap: self.spectral_gap(),
            w2_contraction: self.convergence_rate(t),
            entropy_decay: self.entropy_convergence_rate(t),
            log_sobolev_constant: if self.curvature_k > 0.0 { 2.0 / self.curvature_k } else { f64::INFINITY },
            time: t,
        }
    }
}

/// Convergence report for PLATO belief updates.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct ConvergenceReport {
    pub curvature_k: f64,
    pub spectral_gap: f64,
    pub w2_contraction: f64,
    pub entropy_decay: f64,
    pub log_sobolev_constant: f64,
    pub time: f64,
}

// ─── Spectral Gap Estimation ─────────────────────────────────────────────────

/// Estimate the spectral gap of the Fokker-Planck operator.
pub struct SpectralGapEstimator {
    pub potential: Potential,
    pub diffusion: f64,
}

impl SpectralGapEstimator {
    pub fn new(potential: Potential, diffusion: f64) -> Self {
        SpectralGapEstimator { potential, diffusion }
    }

    /// Lower bound from Bakry-Émery: λ₁ ≥ K.
    pub fn be_lower_bound(&self) -> f64 {
        self.potential.min_hessian_eigenvalue()
    }

    /// Estimate spectral gap via Rayleigh quotient on the discretized operator.
    /// L = -Δ + β∇Φ·∇  (generator of the semigroup)
    /// λ₁ = min_{f⊥1} ⟨Lf, f⟩ / ⟨f, f⟩
    pub fn estimate_rayleigh(&self, n_trials: usize) -> f64 {
        let total = self.potential.values.len();
        let grad = self.potential.gradient();
        let beta = 1.0 / self.diffusion;

        let mut min_gap = f64::INFINITY;

        for _ in 0..n_trials {
            // Random test function (orthogonal to constants)
            let mut f: Vec<f64> = (0..total).map(|_| {
                2.0 * (rand_simple() - 0.5)
            }).collect();
            // Subtract mean
            let mean: f64 = f.iter().sum::<f64>() / total as f64;
            for v in f.iter_mut() { *v -= mean; }

            // Lf = -Δf + β ∇Φ·∇f
            let mut lf = vec![0.0; total];

            // Laplacian of f
            for idx in 0..total {
                let mut rem = idx;
                let mut coords = vec![0usize; self.potential.dim];
                for d in 0..self.potential.dim {
                    coords[d] = rem % self.potential.grid_size;
                    rem /= self.potential.grid_size;
                }
                let mut lap_f = 0.0;
                let mut grad_f = vec![0.0; self.potential.dim];
                for d in 0..self.potential.dim {
                    let h = self.potential.spacing[d];
                    if coords[d] + 1 < self.potential.grid_size && coords[d] > 0 {
                        let mut np = coords.clone();
                        let mut nm = coords.clone();
                        np[d] = coords[d] + 1;
                        nm[d] = coords[d] - 1;
                        let mut idx_p = 0;
                        let mut idx_m = 0;
                        let mut stride = 1;
                        for dd in 0..self.potential.dim {
                            idx_p += np[dd] * stride;
                            idx_m += nm[dd] * stride;
                            stride *= self.potential.grid_size;
                        }
                        lap_f += (f[idx_p] - 2.0 * f[idx] + f[idx_m]) / (h * h);
                        grad_f[d] = (f[idx_p] - f[idx_m]) / (2.0 * h);
                    }
                }
                lf[idx] = -lap_f;
                for d in 0..self.potential.dim {
                    lf[idx] += beta * grad[d][idx] * grad_f[d];
                }
            }

            // Rayleigh quotient
            let num: f64 = f.iter().zip(lf.iter()).map(|(&fi, &li)| fi * li).sum();
            let den: f64 = f.iter().map(|&fi| fi * fi).sum();
            if den > 1e-15 {
                let rq = num / den;
                if rq > 0.0 && rq < min_gap {
                    min_gap = rq;
                }
            }
        }

        if min_gap == f64::INFINITY { 0.0 } else { min_gap }
    }
}

/// Simple deterministic pseudo-random for reproducibility (no external rand dep).
fn rand_simple() -> f64 {
    use std::cell::Cell;
    thread_local! {
        static SEED: Cell<u64> = Cell::new(12345);
    }
    SEED.with(|s| {
        let mut seed = s.get();
        seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1442695040888963407);
        s.set(seed);
        (seed >> 33) as f64 / (1u64 << 31) as f64
    })
}

// ─── Log-Sobolev Inequality ──────────────────────────────────────────────────

/// Verify the log-Sobolev inequality: Ent_μ(f²) ≤ (2/C_LSI) ∫ |∇f|² dμ
pub struct LogSobolev {
    pub c_lsi: f64, // LSI constant
}

impl LogSobolev {
    pub fn from_curvature(k: f64) -> Self {
        LogSobolev {
            c_lsi: if k > 0.0 { 2.0 / k } else { f64::INFINITY },
        }
    }

    /// Check LSI for a given test function f evaluated on a density grid.
    /// Returns (entropy, dirichlet_energy, ratio).
    pub fn verify_lsi(&self, f: &[f64], mu: &Density) -> (f64, f64, f64) {
        let cell_vol = mu.spacing.iter().product::<f64>();
        let n = f.len();

        // f² and its log
        let f2: Vec<f64> = f.iter().map(|&x| x * x).collect();
        let int_f2: f64 = f2.iter().zip(mu.values.iter()).map(|(&f2i, &mui)| f2i * mui).sum::<f64>() * cell_vol;

        // Entropy: ∫ f² ln(f² / ∫f²) dμ = ∫ f² ln(f²) dμ - (∫ f² dμ) ln(∫ f² dμ)
        let mut ent = 0.0;
        for (&f2i, &mui) in f2.iter().zip(mu.values.iter()) {
            if f2i > 0.0 && mui > 0.0 {
                ent += f2i * mui * f2i.ln() * cell_vol;
            }
        }
        if int_f2 > 0.0 {
            ent -= int_f2 * int_f2.ln();
        }

        // Dirichlet energy: ∫ |∇f|² dμ (gradient of f, not f²)
        let mut dirichlet = 0.0;
        for idx in 0..n {
            let mut rem = idx;
            let mut coords = vec![0usize; mu.dim];
            for d in 0..mu.dim {
                coords[d] = rem % mu.grid_size;
                rem /= mu.grid_size;
            }
            for d in 0..mu.dim {
                let h = mu.spacing[d];
                if coords[d] + 1 < mu.grid_size && coords[d] > 0 {
                    let mut np = coords.clone();
                    let mut nm = coords.clone();
                    np[d] = coords[d] + 1;
                    nm[d] = coords[d] - 1;
                    let mut idx_p = 0;
                    let mut idx_m = 0;
                    let mut stride = 1;
                    for dd in 0..mu.dim {
                        idx_p += np[dd] * stride;
                        idx_m += nm[dd] * stride;
                        stride *= mu.grid_size;
                    }
                    let df = (f[idx_p] - f[idx_m]) / (2.0 * h);
                    dirichlet += df * df * mu.values[idx] * cell_vol;
                }
            }
        }

        let ratio = if dirichlet > 1e-15 { ent / dirichlet } else { f64::INFINITY };
        (ent, dirichlet, ratio)
    }

    /// Check that ratio ≤ C_LSI.
    pub fn check_lsi(&self, f: &[f64], mu: &Density) -> bool {
        let (_, _, ratio) = self.verify_lsi(f, mu);
        ratio <= self.c_lsi * 1.1 // tolerance
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    fn make_test_potential() -> Potential {
        Potential::quadratic(1, 21, 0.1, 5.0)
    }

    fn make_test_density() -> Density {
        Density::gaussian(1, 21, 0.1, 1.0)
    }

    // ─── Potential Tests ─────────────────────────────────

    #[test]
    fn test_potential_zeros() {
        let p = Potential::zeros(2, 5, 0.1);
        assert_eq!(p.values.len(), 25);
        assert!(p.values.iter().all(|&v| v == 0.0));
    }

    #[test]
    fn test_potential_quadratic_shape() {
        let p = make_test_potential();
        assert_eq!(p.values.len(), 21);
        // Center value should be 0
        assert_eq!(p.values[10], 0.0);
    }

    #[test]
    fn test_potential_quadratic_values() {
        let p = Potential::quadratic(1, 11, 1.0, 2.0);
        // Φ(0) = 0, Φ(1) = ½·2·1 = 1, Φ(2) = ½·2·4 = 4
        assert!((p.values[5]).abs() < 1e-10); // center
        assert!((p.values[6] - 1.0).abs() < 1e-10); // offset by 1
        assert!((p.values[7] - 4.0).abs() < 1e-10); // offset by 2
    }

    #[test]
    fn test_potential_get_set() {
        let mut p = Potential::zeros(2, 3, 0.1);
        p.set(&[1, 2], 42.0);
        assert_eq!(p.get(&[1, 2]), 42.0);
    }

    #[test]
    fn test_potential_gradient() {
        let p = Potential::quadratic(1, 11, 1.0, 3.0);
        let grad = p.gradient();
        // Gradient of ½·3·x² = 3x
        assert!((grad[0][6] - 3.0).abs() < 0.5); // x=1 → grad=3
    }

    #[test]
    fn test_potential_laplacian() {
        let p = Potential::quadratic(1, 11, 1.0, 3.0);
        let lap = p.laplacian();
        // Laplacian of ½·3·x² = 3
        // Boundary points have zero Laplacian in our finite difference; check interior
        for i in 1..lap.len()-1 {
            assert!((lap[i] - 3.0).abs() < 1.0, "laplacian[{}] = {}", i, lap[i]);
        }
    }

    #[test]
    fn test_potential_min_hessian() {
        let p = Potential::quadratic(1, 11, 1.0, 5.0);
        let k = p.min_hessian_eigenvalue();
        assert!((k - 5.0).abs() < 1.0, "min hessian = {}", k);
    }

    // ─── Density Tests ───────────────────────────────────

    #[test]
    fn test_density_uniform_mass() {
        let d = Density::uniform(1, 11, 0.1);
        assert!((d.total_mass() - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_density_gaussian_mass() {
        let d = Density::gaussian(1, 21, 0.1, 1.0);
        assert!((d.total_mass() - 1.0).abs() < 0.1);
    }

    #[test]
    fn test_density_gaussian_positive() {
        let d = Density::gaussian(1, 21, 0.1, 1.0);
        assert!(d.values.iter().all(|&v| v > 0.0));
    }

    #[test]
    fn test_density_from_values_normalizes() {
        let d = Density::from_values(1, 5, 0.1, vec![1.0, 2.0, 3.0, 2.0, 1.0]);
        assert!((d.total_mass() - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_density_kl_divergence_self() {
        let d = Density::gaussian(1, 21, 0.1, 1.0);
        let kl = d.kl_divergence(&d);
        assert!(kl.abs() < 0.1, "KL divergence to self = {}", kl);
    }

    #[test]
    fn test_density_kl_divergence_positive() {
        let d1 = Density::gaussian(1, 21, 0.1, 1.0);
        let d2 = Density::gaussian(1, 21, 0.1, 2.0);
        let kl = d1.kl_divergence(&d2);
        assert!(kl > 0.0, "KL divergence should be positive: {}", kl);
    }

    #[test]
    fn test_density_entropy_positive() {
        let d = Density::gaussian(1, 21, 0.1, 1.0);
        let h = d.entropy();
        assert!(h > 0.0, "entropy = {}", h);
    }

    #[test]
    fn test_density_second_moment() {
        let d = Density::gaussian(1, 51, 0.1, 2.0);
        let m2 = d.second_moment();
        // For unit-variance Gaussian, E[X²] = σ²
        assert!(m2 > 0.5 && m2 < 5.0, "second moment = {}", m2);
    }

    #[test]
    fn test_density_mean_centered() {
        let d = Density::gaussian(1, 21, 0.1, 1.0);
        let mu = d.mean();
        assert!(mu[0].abs() < 0.5, "mean = {:?}", mu);
    }

    // ─── Fokker-Planck Tests ─────────────────────────────

    #[test]
    fn test_fp_gibbs_is_stationary() {
        let pot = Potential::quadratic(1, 21, 0.1, 5.0);
        let fp = FokkerPlanck::new(pot, 1.0);
        let gibbs = fp.gibbs_measure();
        assert!((gibbs.total_mass() - 1.0).abs() < 0.1);
    }

    #[test]
    fn test_fp_gibbs_centered() {
        let pot = Potential::quadratic(1, 21, 0.1, 5.0);
        let fp = FokkerPlanck::new(pot, 1.0);
        let gibbs = fp.gibbs_measure();
        let mu = gibbs.mean();
        assert!(mu[0].abs() < 0.5);
    }

    #[test]
    fn test_fp_evolve_preserves_mass_approx() {
        let pot = Potential::quadratic(1, 21, 0.1, 5.0);
        let fp = FokkerPlanck::new(pot, 0.5);
        let rho = Density::gaussian(1, 21, 0.1, 2.0);
        let evolved = fp.evolve(&rho, 0.01, 10);
        // Mass should be approximately preserved
        assert!((evolved.total_mass() - 1.0).abs() < 0.3);
    }

    #[test]
    fn test_fp_evolve_toward_gibbs() {
        let pot = Potential::quadratic(1, 21, 0.1, 5.0);
        let fp = FokkerPlanck::new(pot, 0.5);
        let gibbs = fp.gibbs_measure();
        let rho = Density::gaussian(1, 21, 0.1, 2.0);
        let evolved = fp.evolve(&rho, 0.1, 50);
        let kl_before = rho.kl_divergence(&gibbs);
        let kl_after = evolved.kl_divergence(&gibbs);
        // KL should decrease
        assert!(kl_after < kl_before, "KL before = {}, after = {}", kl_before, kl_after);
    }

    #[test]
    fn test_fp_apply_shape() {
        let pot = make_test_potential();
        let fp = FokkerPlanck::new(pot, 1.0);
        let rho = make_test_density();
        let drho = fp.apply(&rho);
        assert_eq!(drho.len(), 21);
    }

    // ─── Time-Reversed Flow Tests ────────────────────────

    #[test]
    fn test_reversed_gradient_shape() {
        let pot = make_test_potential();
        let tr = TimeReversedGradientFlow::new(pot, 0.1);
        let rho = make_test_density();
        let drho = tr.reversed_apply(&rho);
        assert_eq!(drho.len(), 21);
    }

    #[test]
    fn test_gradient_descent_step() {
        let pot = make_test_potential();
        let tr = TimeReversedGradientFlow::new(pot, 0.1);
        let rho = make_test_density();
        let after = tr.gradient_descent_step(&rho, 0.001);
        assert_eq!(after.values.len(), 21);
        assert!((after.total_mass() - 1.0).abs() < 0.5);
    }

    #[test]
    fn test_gradient_descent_converges() {
        let pot = Potential::quadratic(1, 21, 0.1, 5.0);
        let tr = TimeReversedGradientFlow::new(pot, 0.01);
        let rho = Density::gaussian(1, 21, 0.1, 3.0);
        let result = tr.gradient_descent(&rho, 0.5, 100);
        // Should concentrate near the minimum (center)
        let mu = result.mean();
        assert!(mu[0].abs() < 1.0, "mean after descent = {:?}", mu);
    }

    #[test]
    fn test_time_reversal_identity_approx() {
        let pot = Potential::quadratic(1, 11, 0.5, 2.0);
        let tr = TimeReversedGradientFlow::new(pot, 0.1);
        let rho = Density::gaussian(1, 11, 0.5, 1.0);
        let err = tr.verify_time_reversal(&rho, 0.001, 5);
        // Should be small for small dt
        assert!(err < 1.0, "time reversal error = {}", err);
    }

    #[test]
    fn test_forward_vs_reversed_sign() {
        let pot = Potential::quadratic(1, 21, 0.1, 5.0);
        let fp = FokkerPlanck::new(pot.clone(), 0.1);
        let tr = TimeReversedGradientFlow::new(pot, 0.1);
        let rho = Density::gaussian(1, 21, 0.1, 1.0);
        let fwd = fp.apply(&rho);
        let rev = tr.reversed_apply(&rho);
        // Reversed drift should differ from forward
        let mut fwd_sum = 0.0;
        let mut rev_sum = 0.0;
        for i in 0..fwd.len() {
            fwd_sum += fwd[i];
            rev_sum += rev[i];
        }
        // They should generally be different
        assert!((fwd_sum - rev_sum).abs() > 1e-15 || fwd.iter().zip(rev.iter()).any(|(&a, &b)| (a-b).abs() > 1e-15));
    }

    // ─── Bakry-Émery Tests ───────────────────────────────

    #[test]
    fn test_be_curvature_quadratic() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        let k = be.optimal_curvature();
        assert!((k - 5.0).abs() < 1.0, "K = {}", k);
    }

    #[test]
    fn test_be_check_cd_positive() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        assert!(be.check_cd(3.0)); // K=3 < 5
    }

    #[test]
    fn test_be_check_cd_negative() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        assert!(!be.check_cd(10.0)); // K=10 > 5
    }

    #[test]
    fn test_be_spectral_gap() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        let gap = be.spectral_gap();
        assert!(gap > 3.0, "spectral gap = {}", gap);
    }

    #[test]
    fn test_be_log_sobolev() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        let c = be.log_sobolev_constant();
        assert!(c > 0.0 && c < 2.0, "LSI constant = {}", c);
    }

    #[test]
    fn test_be_entropy_decay_bound() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        let bound = be.entropy_decay_bound(1.0, 1.0);
        assert!(bound < 1.0, "decay bound = {}", bound);
        assert!(bound > 0.0);
    }

    #[test]
    fn test_be_entropy_decay_decreases_with_time() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let be = BakryEmery::new(pot);
        let b1 = be.entropy_decay_bound(0.5, 1.0);
        let b2 = be.entropy_decay_bound(1.0, 1.0);
        assert!(b2 < b1);
    }

    // ─── Wasserstein Contraction Tests ───────────────────

    #[test]
    fn test_w2_contraction_bound() {
        let wc = WassersteinContraction::new(5.0);
        let b = wc.contraction_bound(1.0, 1.0);
        assert!(b < 1.0);
        assert!(b > 0.0);
    }

    #[test]
    fn test_w2_contraction_decreases() {
        let wc = WassersteinContraction::new(5.0);
        let b1 = wc.contraction_bound(0.5, 1.0);
        let b2 = wc.contraction_bound(1.0, 1.0);
        assert!(b2 < b1);
    }

    #[test]
    fn test_w2_contraction_rate() {
        let k = 3.0;
        let wc = WassersteinContraction::new(k);
        // At t = 1/K, contraction should be e^{-1}
        let b = wc.contraction_bound(1.0 / k, 1.0);
        assert!((b - 1.0 / E).abs() < 0.01, "contraction at 1/K = {}", b);
    }

    #[test]
    fn test_discrete_w2_symmetric() {
        let wc = WassersteinContraction::new(1.0);
        let d1 = Density::gaussian(1, 11, 0.5, 1.0);
        let d2 = Density::gaussian(1, 11, 0.5, 2.0);
        let w1 = wc.discrete_w2(&d1, &d2);
        let w2 = wc.discrete_w2(&d2, &d1);
        assert!((w1 - w2).abs() < 0.01);
    }

    #[test]
    fn test_discrete_w2_self_zero() {
        let wc = WassersteinContraction::new(1.0);
        let d = Density::gaussian(1, 11, 0.5, 1.0);
        let w = wc.discrete_w2(&d, &d);
        assert!(w < 0.01, "W2 to self = {}", w);
    }

    #[test]
    fn test_discrete_w2_positive() {
        let wc = WassersteinContraction::new(1.0);
        let d1 = Density::gaussian(1, 21, 0.1, 1.0);
        let d2 = Density::gaussian(1, 21, 0.1, 3.0);
        let w = wc.discrete_w2(&d1, &d2);
        assert!(w > 0.0);
    }

    // ─── JKO Scheme Tests ────────────────────────────────

    #[test]
    fn test_jko_functional_finite() {
        let pot = Potential::quadratic(1, 11, 0.5, 3.0);
        let jko = JKOScheme::new(pot, 0.5, 0.01);
        let rho = Density::gaussian(1, 11, 0.5, 1.0);
        let f = jko.jko_functional(&rho, &rho);
        assert!(f.is_finite());
    }

    #[test]
    fn test_jko_step_produces_density() {
        let pot = Potential::quadratic(1, 11, 0.5, 3.0);
        let jko = JKOScheme::new(pot, 0.5, 0.01);
        let rho = Density::gaussian(1, 11, 0.5, 1.0);
        let next = jko.jko_step(&rho);
        assert_eq!(next.values.len(), rho.values.len());
    }

    #[test]
    fn test_jko_step_positive() {
        let pot = Potential::quadratic(1, 11, 0.5, 3.0);
        let jko = JKOScheme::new(pot, 0.5, 0.01);
        let rho = Density::gaussian(1, 11, 0.5, 1.0);
        let next = jko.jko_step(&rho);
        assert!(next.values.iter().all(|&v| v >= 0.0));
    }

    #[test]
    fn test_jko_evolve() {
        let pot = Potential::quadratic(1, 11, 0.5, 3.0);
        let jko = JKOScheme::new(pot, 0.5, 0.01);
        let rho = Density::gaussian(1, 11, 0.5, 1.0);
        let evolved = jko.evolve(&rho, 5);
        assert_eq!(evolved.values.len(), 11);
    }

    #[test]
    fn test_jko_functional_positive() {
        let pot = Potential::quadratic(1, 11, 0.5, 3.0);
        let jko = JKOScheme::new(pot, 0.5, 0.01);
        let d1 = Density::gaussian(1, 11, 0.5, 1.0);
        let d2 = Density::gaussian(1, 11, 0.5, 2.0);
        let f = jko.jko_functional(&d1, &d2);
        assert!(f > 0.0 || f.is_finite());
    }

    // ─── Parameter Manifold Tests ────────────────────────

    #[test]
    fn test_parameter_manifold_gradient_step() {
        let mut pm = ParameterManifold::new(DVector::from_vec(vec![1.0, 2.0, 3.0]), 0.1);
        pm.set_gradient(DVector::from_vec(vec![1.0, 0.0, -1.0]));
        let new_theta = pm.gradient_step();
        assert!((new_theta[0] - 0.9).abs() < 1e-10);
        assert!((new_theta[2] - 3.1).abs() < 1e-10);
    }

    #[test]
    fn test_parameter_manifold_natural_gradient() {
        let mut pm = ParameterManifold::new(DVector::from_vec(vec![1.0, 1.0]), 0.1);
        pm.set_fisher(DMatrix::from_row_slice(2, 2, &[2.0, 0.0, 0.0, 2.0]));
        pm.set_gradient(DVector::from_vec(vec![2.0, 2.0]));
        let new_theta = pm.natural_gradient_step();
        // F^{-1} g = [1/2, 1/2], step = 0.1 * [1/2, 1/2] = [0.05, 0.05]
        assert!((new_theta[0] - 0.9).abs() < 0.01);
    }

    #[test]
    fn test_riemannian_gradient() {
        let mut pm = ParameterManifold::new(DVector::from_vec(vec![0.0; 3]), 0.1);
        pm.set_fisher(DMatrix::from_diagonal(&DVector::from_vec(vec![2.0, 4.0, 1.0])));
        pm.set_gradient(DVector::from_vec(vec![2.0, 4.0, 1.0]));
        let rg = pm.riemannian_gradient();
        assert!((rg[0] - 1.0).abs() < 1e-10);
        assert!((rg[1] - 1.0).abs() < 1e-10);
        assert!((rg[2] - 1.0).abs() < 1e-10);
    }

    #[test]
    fn test_riemannian_norm() {
        let mut pm = ParameterManifold::new(DVector::from_vec(vec![0.0; 2]), 0.1);
        pm.set_fisher(DMatrix::from_row_slice(2, 2, &[1.0, 0.0, 0.0, 4.0]));
        let v = DVector::from_vec(vec![1.0, 1.0]);
        let norm = pm.riemannian_norm(&v);
        // v^T F v = 1*1 + 4*1 = 5, sqrt(5)
        assert!((norm - 5.0_f64.sqrt()).abs() < 1e-10);
    }

    #[test]
    fn test_parameter_manifold_identity_fisher() {
        let mut pm = ParameterManifold::new(DVector::from_vec(vec![1.0, 2.0]), 0.1);
        pm.set_gradient(DVector::from_vec(vec![1.0, 1.0]));
        let rg = pm.riemannian_gradient();
        assert!((rg[0] - 1.0).abs() < 1e-10);
        assert!((rg[1] - 1.0).abs() < 1e-10);
    }

    // ─── Fisher-Ricci Tests ──────────────────────────────

    #[test]
    fn test_fisher_ricci_constant_fisher_zero_curvature() {
        let fr = FisherRicci::from_fisher(DMatrix::identity(3, 3));
        let ricci = fr.ricci_tensor();
        assert_eq!(ricci.nrows(), 3);
        // Zero Christoffel → zero Ricci
        assert!(ricci.iter().all(|&v| v.abs() < 1e-10));
    }

    #[test]
    fn test_fisher_ricci_scalar_curvature_flat() {
        let fr = FisherRicci::from_fisher(DMatrix::identity(2, 2));
        let sc = fr.scalar_curvature();
        assert!(sc.abs() < 1e-10);
    }

    #[test]
    fn test_fisher_ricci_direction_flat() {
        let fr = FisherRicci::from_fisher(DMatrix::identity(2, 2));
        let v = DVector::from_vec(vec![1.0, 0.0]);
        let rc = fr.ricci_curvature_direction(&v);
        assert!(rc.abs() < 1e-10);
    }

    #[test]
    fn test_fisher_ricci_min_flat() {
        let fr = FisherRicci::from_fisher(DMatrix::identity(2, 2));
        let min_r = fr.min_ricci_curvature();
        assert!(min_r.abs() < 1e-10);
    }

    #[test]
    fn test_fisher_ricci_check_cd_flat() {
        let fr = FisherRicci::from_fisher(DMatrix::identity(2, 2));
        assert!(fr.check_cd(0.0));
        assert!(!fr.check_cd(0.1));
    }

    #[test]
    fn test_fisher_ricci_from_exponential_family() {
        let d2 = DMatrix::from_row_slice(2, 2, &[2.0, 0.5, 0.5, 2.0]);
        let d3_0 = DMatrix::from_row_slice(2, 2, &[0.1, 0.0, 0.0, 0.1]);
        let d3_1 = DMatrix::from_row_slice(2, 2, &[0.0, 0.1, 0.1, 0.0]);
        let fr = FisherRicci::from_exponential_family(d2, &[d3_0, d3_1]);
        let sc = fr.scalar_curvature();
        assert!(sc.is_finite());
    }

    // ─── Spectral Gap Tests ──────────────────────────────

    #[test]
    fn test_spectral_gap_be_bound() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let sge = SpectralGapEstimator::new(pot, 1.0);
        let gap = sge.be_lower_bound();
        assert!(gap > 3.0);
    }

    #[test]
    fn test_spectral_gap_otto_villani() {
        let pot = Potential::quadratic(1, 11, 1.0, 5.0);
        let sge = SpectralGapEstimator::new(pot, 1.0);
        // Otto-Villani: λ₁ ≥ K (BE curvature)
        let be_bound = sge.be_lower_bound();
        let rayleigh = sge.estimate_rayleigh(20);
        // Rayleigh estimate should be ≥ BE bound (approximately)
        assert!(rayleigh > 0.0);
    }

    #[test]
    fn test_spectral_gap_positive_for_strongly_convex() {
        let pot = Potential::quadratic(1, 11, 1.0, 10.0);
        let sge = SpectralGapEstimator::new(pot, 1.0);
        let gap = sge.be_lower_bound();
        assert!(gap > 5.0);
    }

    // ─── Log-Sobolev Tests ───────────────────────────────

    #[test]
    fn test_log_sobolev_from_curvature() {
        let ls = LogSobolev::from_curvature(5.0);
        assert!((ls.c_lsi - 0.4).abs() < 1e-10);
    }

    #[test]
    fn test_log_sobolev_verify_lsi() {
        let ls = LogSobolev::from_curvature(2.0);
        let mu = Density::gaussian(1, 21, 0.1, 0.5);
        // Simple test function: f = x (linear)
        let half = 10.0;
        let f: Vec<f64> = (0..21).map(|i| (i as f64 - half) * 0.1).collect();
        let (ent, dir, ratio) = ls.verify_lsi(&f, &mu);
        assert!(ent.is_finite());
        assert!(dir >= 0.0);
    }

    #[test]
    fn test_log_sobolev_zero_curvature() {
        let ls = LogSobolev::from_curvature(0.0);
        assert!(ls.c_lsi.is_infinite());
    }

    #[test]
    fn test_log_sobolev_check() {
        let ls = LogSobolev::from_curvature(1.0);
        let mu = Density::gaussian(1, 21, 0.1, 1.0);
        let f: Vec<f64> = (0..21).map(|i| (i as f64 - 10.0) * 0.1).collect();
        // Just verify it doesn't panic
        let _ = ls.check_lsi(&f, &mu);
    }

    // ─── PLATO Agent Tests ───────────────────────────────

    #[test]
    fn test_plato_init_belief() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let belief = plato.init_gaussian_belief(1.0);
        assert!((belief.total_mass() - 1.0).abs() < 0.1);
    }

    #[test]
    fn test_plato_evolve_belief() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let belief = plato.init_gaussian_belief(1.0);
        let evolved = plato.evolve_belief(&belief, 0.01, 10);
        assert_eq!(evolved.values.len(), 21);
    }

    #[test]
    fn test_plato_convergence_rate() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let rate = plato.convergence_rate(1.0);
        assert!(rate < 1.0);
        assert!(rate > 0.0);
    }

    #[test]
    fn test_plato_entropy_convergence_rate() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let rate = plato.entropy_convergence_rate(1.0);
        assert!(rate < 1.0);
    }

    #[test]
    fn test_plato_spectral_gap() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        assert!((plato.spectral_gap() - 5.0).abs() < 1e-10);
    }

    #[test]
    fn test_plato_mixing_time_w2() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let t = plato.mixing_time_w2(0.01, 1.0);
        assert!(t > 0.0 && t.is_finite());
    }

    #[test]
    fn test_plato_mixing_time_entropy() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let t = plato.mixing_time_entropy(0.01, 1.0);
        assert!(t > 0.0 && t.is_finite());
    }

    #[test]
    fn test_plato_mixing_time_zero_curvature() {
        let plato = PlatoBeliefUpdate::new(0.0, 0.5, 1, 21, 0.1);
        assert!(plato.mixing_time_w2(0.01, 1.0).is_infinite());
    }

    #[test]
    fn test_plato_convergence_report() {
        let plato = PlatoBeliefUpdate::new(5.0, 0.5, 1, 21, 0.1);
        let report = plato.convergence_analysis(1.0);
        assert!((report.curvature_k - 5.0).abs() < 1e-10);
        assert!((report.spectral_gap - 5.0).abs() < 1e-10);
        assert!(report.w2_contraction > 0.0 && report.w2_contraction < 1.0);
        assert!(report.entropy_decay > 0.0 && report.entropy_decay < 1.0);
        assert!(report.log_sobolev_constant > 0.0);
    }

    // ─── Convergence Report Serialization ────────────────

    #[test]
    fn test_convergence_report_serde() {
        let report = ConvergenceReport {
            curvature_k: 5.0,
            spectral_gap: 5.0,
            w2_contraction: 0.1,
            entropy_decay: 0.01,
            log_sobolev_constant: 0.4,
            time: 1.0,
        };
        let json = serde_json::to_string(&report).unwrap();
        let back: ConvergenceReport = serde_json::from_str(&json).unwrap();
        assert!((back.curvature_k - 5.0).abs() < 1e-10);
        assert!((back.time - 1.0).abs() < 1e-10);
    }

    // ─── Integration Tests ───────────────────────────────

    #[test]
    fn test_full_pipeline_kimi_theorem() {
        // Full pipeline: potential → FP → BE → spectral gap → contraction → PLATO
        let dim = 1;
        let grid = 21;
        let spacing = 0.1;
        let k = 5.0;
        let diffusion = 0.5;

        // 1. Create potential
        let pot = Potential::quadratic(dim, grid, spacing, k);

        // 2. Verify CD(K,∞)
        let be = BakryEmery::new(pot.clone());
        assert!(be.check_cd(k * 0.8));

        // 3. FP evolve
        let fp = FokkerPlanck::new(pot.clone(), diffusion);
        let rho = Density::gaussian(dim, grid, spacing, 2.0);
        let gibbs = fp.gibbs_measure();
        let evolved = fp.evolve(&rho, 0.1, 50);

        // 4. KL divergence should decrease
        let kl0 = rho.kl_divergence(&gibbs);
        let kl1 = evolved.kl_divergence(&gibbs);
        assert!(kl1 < kl0, "KL should decrease: {} → {}", kl0, kl1);

        // 5. Spectral gap ≥ K
        let sge = SpectralGapEstimator::new(pot.clone(), diffusion);
        assert!(sge.be_lower_bound() >= k * 0.5);

        // 6. PLATO convergence
        let plato = PlatoBeliefUpdate::new(k, diffusion, dim, grid, spacing);
        let report = plato.convergence_analysis(1.0);
        assert!(report.w2_contraction < 1.0);
    }

    #[test]
    fn test_integration_jko_fp_agreement() {
        // JKO and FP should give similar results for small τ
        let pot = Potential::quadratic(1, 11, 0.5, 3.0);
        let diffusion = 0.5;
        let rho = Density::gaussian(1, 11, 0.5, 1.0);

        let fp = FokkerPlanck::new(pot.clone(), diffusion);
        let fp_result = fp.evolve(&rho, 0.01, 5);

        let jko = JKOScheme::new(pot, diffusion, 0.002);
        let jko_result = jko.evolve(&rho, 5);

        // Both should produce valid densities
        assert!((fp_result.total_mass() - 1.0).abs() < 0.5);
        assert!((jko_result.total_mass() - 1.0).abs() < 0.5);
    }

    #[test]
    fn test_integration_fisher_ricci_natural_gradient() {
        // Natural gradient descent uses Fisher metric → connects to Ricci curvature
        let theta = DVector::from_vec(vec![1.0, -1.0]);
        let mut pm = ParameterManifold::new(theta, 0.1);

        let fisher = DMatrix::from_row_slice(2, 2, &[3.0, 0.5, 0.5, 3.0]);
        pm.set_fisher(fisher.clone());
        pm.set_gradient(DVector::from_vec(vec![3.0, -3.0]));

        let rg = pm.riemannian_gradient();
        let _new_theta = pm.natural_gradient_step();

        let fr = FisherRicci::from_fisher(fisher);
        let sc = fr.scalar_curvature();
        // Zero Christoffel for constant Fisher
        assert!(sc.abs() < 1e-10);
    }
}
